export const PRODUCTS = [
  {
    _id: 'p1',
    name: 'Gota Biri (Urad Dal)',
    shortName: 'Gota Biri',
    image: '/gota-biri.png',
    price: 150,
    weight: '1kg',
    category: 'Dal',
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 320,
    description: 'Premium whole urad dal sourced directly from Odisha farms. Rich in protein and fiber, perfect for dal makhani, idli batter and more.',
    stock: 50,
    color: '#1a1a1a',
    accent: '#888',
  },
  {
    _id: 'p2',
    name: 'Red Rice (Kumara Chaula)',
    shortName: 'Red Rice',
    image: '/red-rice.png',
    price: 120,
    weight: '1kg',
    category: 'Rice',
    badge: null,
    rating: 4.8,
    reviews: 215,
    description: 'Traditional Odia red rice packed with antioxidants and minerals. Nutty flavor with a chewy texture, ideal for everyday cooking.',
    stock: 80,
    color: '#3a0808',
    accent: '#8B2014',
  },
  {
    _id: 'p3',
    name: 'Moong Dal (Split)',
    shortName: 'Moong Dal',
    image: '/moong-dal.png',
    price: 110,
    weight: '1kg',
    category: 'Dal',
    badge: null,
    rating: 4.7,
    reviews: 198,
    description: 'Light and easily digestible split moong dal from Odisha. Perfect for khichdi, soups, and a variety of healthy dishes.',
    stock: 65,
    color: '#1a1800',
    accent: '#C4A200',
  },
  {
    _id: 'p4',
    name: 'Toor Dal',
    shortName: 'Toor Dal',
    image: '/toor-dal.png',
    price: 130,
    weight: '1kg',
    category: 'Dal',
    badge: null,
    rating: 4.8,
    reviews: 175,
    description: 'Authentic Odia toor dal with rich earthy flavor. A kitchen staple for dal tadka, sambar and traditional Odia thali.',
    stock: 70,
    color: '#1a0d00',
    accent: '#D4830A',
  },
  {
    _id: 'p5',
    name: 'Kolatha (Horse Gram)',
    shortName: 'Kolatha',
    image: '/kolatha.png',
    price: 90,
    weight: '1kg',
    category: 'Dal',
    badge: 'Organic',
    rating: 4.6,
    reviews: 142,
    description: 'Nutritious horse gram traditionally grown in Odisha. High in protein, iron and antioxidants — a superfood dal.',
    stock: 45,
    color: '#1a0d08',
    accent: '#8B4513',
  },
  {
    _id: 'p6',
    name: 'Chana Dal',
    shortName: 'Chana Dal',
    image: '/chana-dal.png',
    price: 115,
    weight: '1kg',
    category: 'Dal',
    badge: null,
    rating: 4.7,
    reviews: 160,
    description: 'Freshly milled split bengal gram with vibrant yellow color. Adds richness to curries, halwa and snacks.',
    stock: 55,
    color: '#1a1400',
    accent: '#D4A800',
  },
  {
    _id: 'p7',
    name: 'Sona Masoori Rice',
    shortName: 'Sona Masoori',
    image: '/sona-masoori.png',
    price: 100,
    weight: '1kg',
    category: 'Rice',
    badge: null,
    rating: 4.8,
    reviews: 210,
    description: 'Premium Sona Masoori rice — lightweight, low starch, and aromatic. Perfect for everyday meals and biryani.',
    stock: 90,
    color: '#0d0d0d',
    accent: '#C8C8A0',
  },
  {
    _id: 'p8',
    name: 'Masur Dal (Red Lentil)',
    shortName: 'Masur Dal',
    image: '/masur-dal.png',
    price: 105,
    weight: '1kg',
    category: 'Dal',
    badge: 'New',
    rating: 4.6,
    reviews: 88,
    description: 'Tender red lentils that cook quickly. Rich in iron and folate, perfect for soups, dals and curries.',
    stock: 60,
    color: '#1a0600',
    accent: '#C04020',
  },
]

export const CATEGORIES = ['All', 'Rice', 'Dal']

export const REVIEWS = [
  { id: 1, name: 'Sushma P.', city: 'Bhubaneswar', rating: 5, text: 'Excellent quality Gota Biri! Cooked perfectly and the taste is just amazing. Finally found authentic Odia products online.' },
  { id: 2, name: 'Rajesh K.', city: 'Cuttack', rating: 5, text: 'Red rice quality is top-notch. Packaging was neat and delivery was on time. Will definitely order again from OdishaShop!' },
  { id: 3, name: 'Ankita M.', city: 'Bangalore', rating: 5, text: 'Finally a trustworthy place to get authentic products from Odisha. The dal varieties are pure and completely fresh.' },
]
